### ISSUE TITLE
deadlink in README.md

### ISSUE THREAD

**Issue by overseers-desk** [damko/xkb_kinesis_advantage_dvorak_layout#2]
Hi links to [Kinesis Advantage Dvorak US layout](https://camo.githubusercontent.com/b04c7095745cb6dec7e08324edebe1bcf1ea69744f250259ac8a95022b8a0f3d/687474703a2f2f64726976652e676f6f676c652e636f6d2f75633f69643d304238545075743668667748306569314753335a6b5347787053566b) is dead

and is it more reasonable to copy the linked content into the repo?

On a side note have you considered making a deb package?

**Comment by damko** [comment]
> Hi links to [Kinesis Advantage Dvorak US layout](https://camo.githubusercontent.com/b04c7095745cb6dec7e08324edebe1bcf1ea69744f250259ac8a95022b8a0f3d/687474703a2f2f64726976652e676f6f676c652e636f6d2f75633f69643d304238545075743668667748306569314753335a6b5347787053566b) is dead
 
yes indeed. Thank you for reporting this. I've updated the README accordingly. 

I don't even remember what the content was but I suppose it was just a picture showing the keyboard layout

> and is it more reasonable to copy the linked content into the repo?
indeed it is and usually I do. I don't remember why this was linked outside

> 
> On a side note have you considered making a deb package?

Yes but the deb package is a core debian package and I think that no debian developer would accept to add such a specific setting in a core package as it doesn't make any sense.
Rather than that it would make sense to update the xbd directory structure so that it can allow user settings without having them overwritten by a core update. But that's beyond Debian.

**Comment by overseers-desk** [comment]
Do you think it's possible to write a deb package that installs files into /usr/share/X11/xkb/* instead of changing what is already in xkb-data?

One concern is gracefully fallback. When user installed such a deb package, selected your layout, then de-installed it, they have no layout. some scripting may be needed to restore layout to a system default one or let user choose when apt-get remove.

The other is if we can successfully tell any X11 session to reload xkb after apt-get install.

I ask because I have a similar project, better pool the efforts: https://github.com/SmartLayer/MathLingua-Layout

**Comment by damko** [comment]
> Do you think it's possible to write a deb package that installs files into /usr/share/X11/xkb/* instead of changing what is already in xkb-data?

It is possible and not too hard but I would not advise it. I'd rather go for a tgz package. In the end, a `.deb` package is just a tgz on steroids (with hooks aka scripts that are executed in different moments of the installation process).

With a `.tgz` it would work this way:

```
# .tgz creation
tar zcx xkb.tgz xkb

# Usage:
cd /usr/share/X11
tar zxf _path_/xkb.tgz
```
If you are looking for a way to distribute your project to the general public, you can create:

* a skeleton of the xkb folder and subfolders
* copy there your file
* create the `.tgz` as shown above

I'm not sure whether this helps

P.S.: your project is SO cool! bravo!
P.S.2: this pic https://github.com/SmartLayer/MathLingua-Layout/blob/master/layout.png should not have a transparent background otherwise it can not be seen on browsers with dark mode activated

**Comment by damko** [comment]
Also if you need a more elaborated installation process, maybe you could write a `setup.sh` bash script

**Comment by damko** [comment]
I added your project to my README

**Comment by damko** [comment]
If I know mathematicians well enough, you are already googling "deb package howto". ;-)

Let me give you a hand. I took the liberty to make an empty skeleton of what you need to create a rudimental but complete `.deb` package.

https://github.com/damko/deb-demo-package

I hope it helps

**Comment by overseers-desk** [comment]
Thanks, I fixed the PNG problem. I'll check the links you provided! If I come to package it I'll package your project too. I was concerned of not dooming user when they apt-get remove and are no longer able to type.
